### ISSUE TITLE
anon_user "cannot import name settings"

### ISSUE THREAD

**Issue by ykgoon** [ASKBOT/askbot-devel#452]
When deploying with wsgi, I'm get this error.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 171, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.5.12-py2.7.egg/django/core/handlers/wsgi.py", line 236, in __call__
    self.load_middleware()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.5.12-py2.7.egg/django/core/handlers/base.py", line 51, in load_middleware
    raise exceptions.ImproperlyConfigured('Error importing middleware %s: "%s"' % (mw_module, e))
ImproperlyConfigured: Error importing middleware askbot.middleware.anon_user: "cannot import name settings"
```

It's fine when running with django test server.

Server details: Ubuntu 14.04, nginx, gunicorn.

**Comment by ykgoon** [comment]
After further investigation, I think it's because Django couldn't locate askbot middleware in general. I've already ran `python setup.py install`, what did I miss here?

**Comment by evgenyfadeev** [comment]
sounds like an issue with python path
