### ISSUE TITLE
'SortedDict' object has no attribute 'insert'

### ISSUE THREAD

**Issue by amirgon** [ASKBOT/askbot-devel#517]
I've started evaluating AskBot for our organization.  
After installing AskBot + postgresql, running on development server, AskBot seem to work fine until I try to access the Settings.   
`.../settings/QA_SITE_SETTINGS/#id_QA_SITE_SETTINGS__APP_URL__en`    

Then I get this error:

> ` AttributeError at /settings/QA_SITE_SETTINGS/
> 'SortedDict' object has no attribute 'insert'`

[Here is a link to the error page I get ](http://htmlpreview.github.io/?https://gist.githubusercontent.com/amirgon/4cee430a181104568643/raw/dc61d7c118fcf7bacd757edf54dd8b7642aa96ad/AttributeError%2520at%2520_settings_QA_SITE_SETTINGS_.html)  

It seems that some of the settings work ok (for example .../settings/LICENSE_SETTINGS/) and others give the same error (for example, .../settings/FLATPAGES/)

Any idea?

**Comment by amirgon** [comment]
`SortedDict` is deprecated and does not contain `insert` method any more, as of Django 1.7.  
See [related question](http://stackoverflow.com/questions/33395803/sorteddict-object-has-no-attribute-insert)

**Comment by evgenyfadeev** [comment]
Thank you, will be fixed tomorrow.

On Wed, Oct 28, 2015 at 7:57 PM, amirgon <notifications@github.com> wrote:

> SortedDict is deprecated and does not contain insert method any more, as
> of Django 1.7.
>
> See related question
> <http://stackoverflow.com/questions/33395803/sorteddict-object-has-no-attribute-insert>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ASKBOT/askbot-devel/issues/517#issuecomment-151909007>
> .
>



-- 
Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by lnthanh** [comment]
Hi. The page "Settings → External Services → Keys for external services" has this error too.

**Comment by bmauter** [comment]
Hi, I'm probably not seeing it right (I'm a Java guy), but it looks like SortedDict is still in the source (example:  forms.py).

**Comment by daniel1943** [comment]
Confirming problem on dj-18 branch.

**Comment by daniel1943** [comment]
I am big newbie but this seemed to make it work for me(very likely terrible solution!!!!!, be careful):

Edit:
myprojectenv\lib\python2.7\site-packages\askbot-0.9.0-py2.7.egg\askbot\deps\livesettings\values.py

Add this to imports:

    from collections import OrderedDict

Line 293 replace with:

    langs_dict = OrderedDict(django_settings.LANGUAGES)

Few lines lower replace first line with second one.

    # langs_dict(0, default_code, default_name)
    langs_dict[0] = default_code, default_name

**Comment by amirgon** [comment]
@evgenyfadeev - Are there any plans to fix this?

**Comment by bmauter** [comment]
But SortedDict appears in several places, not just values.py.

**Comment by evgenyfadeev** [comment]
True, but hopefully not breaking other things at the moment.
Maybe worth opening another issue to replace the SortedDict.

On Thu, Nov 19, 2015 at 7:20 PM, Brian Mauter <notifications@github.com>
wrote:

> But SortedDict appears in several places, not just values.py.
>
> > On Nov 19, 2015, at 9:49 AM, Evgeny Fadeev <notifications@github.com>
> wrote:
> >
> > Closed #517 <https://github.com/ASKBOT/askbot-devel/issues/517> via
> e3441e2 <
> https://github.com/ASKBOT/askbot-devel/commit/e3441e2a7a39b509bf5b705f4223c94e8214d97d
> >.
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/ASKBOT/askbot-devel/issues/517#event-469315067>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ASKBOT/askbot-devel/issues/517#issuecomment-158106615>
> .
>



-- 
Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by DhruvK95** [comment]
I am having an error that may be related to this:

`python manage.py runserver
Unhandled exception in thread started by <function wrapper at 0x103e3bb90>
Traceback (most recent call last):
  File "/Users/Dhruv/askbot_trial/venv/lib/python2.7/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/Users/Dhruv/askbot_trial/venv/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/Users/Dhruv/askbot_trial/venv/lib/python2.7/site-packages/django/utils/autoreload.py", line 250, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/Dhruv/askbot_trial/venv/lib/python2.7/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/Users/Dhruv/askbot_trial/venv/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Dhruv/askbot_trial/venv/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/Dhruv/askbot_trial/venv/lib/python2.7/site-packages/django/apps/config.py", line 127, in create
    import_module(entry)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/Dhruv/askbot_trial/venv/lib/python2.7/site-packages/askbot/deps/livesettings/__init__.py", line 14, in <module>
    from askbot.deps.livesettings.functions import *
  File "/Users/Dhruv/askbot_trial/venv/lib/python2.7/site-packages/askbot/deps/livesettings/functions.py", line 2, in <module>
    from askbot.deps.livesettings import values
  File "/Users/Dhruv/askbot_trial/venv/lib/python2.7/site-packages/askbot/deps/livesettings/values.py", line 12, in <module>
    from django.utils.datastructures import SortedDict
ImportError: cannot import name SortedDict
`
I had askbot installed and running properly. Then I wanted to add another app I wrote to the current project running askbot. So I installed the requirements.txt for that other project and tried running `runserver` again and I got the above error. 

The list of requirements for the other project is as follows:

`
certifi==2017.7.27.1
chardet==3.0.4
coreapi==2.3.1
coreschema==0.0.4
Django==1.11
django-annoying==0.10.3
django-filter==1.0.4
django-hitcount==1.2.2
django-markdown-app==0.9.2
django-qa==0.9.1
django-rest-swagger==2.1.2
django-taggit==0.22.1
djangorestframework==3.6.4
facebook-sdk==2.0.0
googlemaps==2.5.1
idna==2.6
itypes==1.1.0
Jinja2==2.9.6
Markdown==2.6.9
MarkupSafe==1.0
openapi-codec==1.3.2
pytz==2017.2
requests==2.18.4
simplejson==3.11.1
uritemplate==3.0.0
urllib3==1.22
`

 I am not sure which of these packages caused this error..

**Comment by DhruvK95** [comment]
I am having an error that may be related to this:

```
python manage.py runserver
Unhandled exception in thread started by <function wrapper at 0x103e3bb90>
Traceback (most recent call last):
  File "/Users/Dhruv/askbot_trial/venv/lib/python2.7/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/Users/Dhruv/askbot_trial/venv/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/Users/Dhruv/askbot_trial/venv/lib/python2.7/site-packages/django/utils/autoreload.py", line 250, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/Dhruv/askbot_trial/venv/lib/python2.7/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/Users/Dhruv/askbot_trial/venv/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Dhruv/askbot_trial/venv/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/Dhruv/askbot_trial/venv/lib/python2.7/site-packages/django/apps/config.py", line 127, in create
    import_module(entry)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/Dhruv/askbot_trial/venv/lib/python2.7/site-packages/askbot/deps/livesettings/__init__.py", line 14, in <module>
    from askbot.deps.livesettings.functions import *
  File "/Users/Dhruv/askbot_trial/venv/lib/python2.7/site-packages/askbot/deps/livesettings/functions.py", line 2, in <module>
    from askbot.deps.livesettings import values
  File "/Users/Dhruv/askbot_trial/venv/lib/python2.7/site-packages/askbot/deps/livesettings/values.py", line 12, in <module>
    from django.utils.datastructures import SortedDict
ImportError: cannot import name SortedDict

```
I had askbot installed and running properly. Then I wanted to add another app I wrote to the current project running askbot. So I installed the requirements.txt for that other project and tried running runserver again and I got the above error.

The list of requirements for the other project is as follows:

```
certifi==2017.7.27.1
chardet==3.0.4
coreapi==2.3.1
coreschema==0.0.4
Django==1.11
django-annoying==0.10.3
django-filter==1.0.4
django-hitcount==1.2.2
django-markdown-app==0.9.2
django-qa==0.9.1
django-rest-swagger==2.1.2
django-taggit==0.22.1
djangorestframework==3.6.4
facebook-sdk==2.0.0
googlemaps==2.5.1
idna==2.6
itypes==1.1.0
Jinja2==2.9.6
Markdown==2.6.9
MarkupSafe==1.0
openapi-codec==1.3.2
pytz==2017.2
requests==2.18.4
simplejson==3.11.1
uritemplate==3.0.0
urllib3==1.22

```
I am not sure which of these packages caused this error..
