### ISSUE TITLE
rename_tags causes an exception

### ISSUE THREAD

**Issue by amirgon** [ASKBOT/askbot-devel#541]
After running `rename_tags`, I get `django.core.exceptions.FieldError: Cannot resolve keyword 'status' into field.`

Here is the full trace:

```
$ ./manage.py rename_tags --from "visuat-studio-2015" --to "visual-studio-2015"
WARNING!!! You are using a 'locmem' (local memory) caching backend,
which is OK for a low volume site running on a single-process server.
For a multi-process configuration it is neccessary to have a production
cache system, such as redis or memcached.

With local memory caching and multi-process setup you might intermittently
see outdated content on your site.

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/evelab/projects/askbot-devel/askbot/management/commands/rename_tags.py", line 144, in handle
    admin = get_admin(seed_user_id = options['user_id'])
  File "/home/evelab/projects/askbot-devel/askbot/management/commands/rename_tags.py", line 18, in get_admin
    admin = api.get_admin(seed_user_id = seed_user_id)
  File "/home/evelab/projects/askbot-devel/askbot/api.py", line 63, in get_admin
    Q(is_superuser=True) | Q(status='m')
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 691, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 709, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1331, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1353, in _add_q
    current_negated)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1358, in _add_q
    current_negated=current_negated, connector=connector)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1182, in build_filter
    lookups, parts, reffed_aggregate = self.solve_lookup_type(arg)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1120, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1427, in names_to_path
    self.raise_field_error(opts, name)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1433, in raise_field_error
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'status' into field. Choices are: _message_set, activity, activityauditstatus, anonymousanswer, anonymousquestion, askbot_profile, avatar, award_user, badges, bulktagsubscription, created_tags, date_joined, deleted_posts, deleted_tags, draft_answers, draftquestion, email, endorsed_posts, first_name, followed_threads, followrecord, group_membership, group_messaging_sent_messages, groups, id, incoming_activity, is_active, is_staff, is_superuser, last_edited_posts, last_login, last_name, lastvisittime, locked_posts, logentry, messagememo, notification_subscriptions, password, postflagreason, postrevision, postrevisions, posts, question_views, replyaddress, repute, senderlist, suggested_tags, tag_selections, tag_synonyms, thread, unreadinboxcounter, unused_favorite_threads, unused_last_active_in_threads, user_favorite_questions, user_permissions, userassociation, username, userpasswordqueue, votes
```

**Comment by evgenyfadeev** [comment]
This change similar to commit 0d3a224... is already present in the master branch, therefore fixed.
