### ISSUE TITLE
python manage.py syncdb fails with django warnings

### ISSUE THREAD

**Issue by sconrod-tester** [ASKBOT/askbot-devel#544]
root@dev-tools-125:~/askbot-devel# python manage.py syncdb
WARNING!!! You are using a 'locmem' (local memory) caching backend,
which is OK for a low volume site running on a single-process server.
For a multi-process configuration it is neccessary to have a production
cache system, such as redis or memcached.

With local memory caching and multi-process setup you might intermittently
see outdated content on your site.

System check identified some issues:

WARNINGS:
django_authopenid.UserPasswordQueue.user: (fields.W342) Setting unique=True on a ForeignKey has the same eff OneToOneField.
        HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
group_messaging.SenderList.recipient: (fields.W342) Setting unique=True on a ForeignKey has the same effect ToOneField.
        HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
Operations to perform:
  Synchronize unmigrated apps: captcha, djkombu, staticfiles, tinymce, messages, keyedcache, sitemaps, comprcountries, humanize
  Apply all migrations: followit, livesettings, group_messaging, django_authopenid, sessions, admin, djcelerh, sites, askbot, contenttypes, avatar
Synchronizing apps without migrations:
  Creating tables...
    Creating table djkombu_queue
    Creating table djkombu_message
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying askbot.0001_initial... OK
  Applying askbot.0002_auto_20151026_0715... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying avatar.0001_initial... OK
  Applying django_authopenid.0001_initial... OK
  Applying djcelery.0001_initial... OK
  Applying followit.0001_initial... OK
  Applying group_messaging.0001_initial... OK
  Applying sites.0001_initial... OK
  Applying livesettings.0001_initial... OK
  Applying robots.0001_initial... OK
  Applying sessions.0001_initial... OK

You have installed Django's auth system, and don't have any superusers defined.
Would you like to create one now? (yes/no): yes
Username (leave blank to use 'root'):
Email address: 
Password:
Password (again):
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.7-py2.7.egg/django/core/management/__init__.py", lecute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.7-py2.7.egg/django/core/management/__init__.py", lecute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.7-py2.7.egg/django/core/management/base.py", line om_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.7-py2.7.egg/django/core/management/base.py", line e
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.7-py2.7.egg/django/core/management/commands/syncdb in handle
    call_command("createsuperuser", interactive=True, database=options['database'])
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.7-py2.7.egg/django/core/management/__init__.py", lll_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.7-py2.7.egg/django/contrib/auth/management/commandser.py", line 50, in execute
    return super(Command, self).execute(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.7-py2.7.egg/django/core/management/base.py", line e
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.7-py2.7.egg/django/contrib/auth/management/commandser.py", line 149, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.7-py2.7.egg/django/contrib/auth/models.py", line 1superuser
    **extra_fields)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.7-py2.7.egg/django/contrib/auth/models.py", line 1_user
    user.save(using=self._db)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.7-py2.7.egg/django/db/models/base.py", line 734, i
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.7-py2.7.egg/django/db/models/base.py", line 771, i
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.7-py2.7.egg/django/dispatch/dispatcher.py", line 1
    response = receiver(signal=self, sender=sender, **named)
  File "/root/askbot-devel/askbot/models/__init__.py", line 3920, in add_missing_subscriptions
    instance.add_missing_askbot_subscriptions()
  File "/root/askbot-devel/askbot/models/__init__.py", line 2371, in user_add_missing_askbot_subscriptions
    form = forms.EditUserEmailFeedsForm()
  File "/root/askbot-devel/askbot/forms.py", line 1607, in __init__
    ('asked_by_me', EmailFeedSettingField(label=askbot_settings.WORDS_ASKED_BY_ME)),
  File "/root/askbot-devel/askbot/conf/settings_wrapper.py", line 67, in __getattr__
    return getattr(self.__instance, key).value
  File "/root/askbot-devel/askbot/deps/livesettings/values.py", line 457, in value
    val = self._value()
  File "/root/askbot-devel/askbot/deps/livesettings/values.py", line 348, in _value
    key += '_' + format_setting_name(lang)
  File "/root/askbot-devel/askbot/utils/functions.py", line 47, in format_setting_name
    token = token.replace(' ', '_')
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by hlj2722** [comment]
I also have this problem in 0.10 version

**Comment by nicholasamorim** [comment]
Happens both on 0.10 and on master branch.

Seems to be caused by `get_language()`from `django.utils.translation` returning None.

According to Django [docs](https://docs.djangoproject.com/en/1.9/ref/utils/#django.utils.translation.get_language) it can return None but the code is not ready for it.

Funny thing is, this code only runs if self.localized is True. Its default value is False. So there is some other point in the code that is passing localized=True even if there is no language.

I could fix it, but not sure what is the expected behaviour.

**Comment by evgenyfadeev** [comment]
@nicholasamorim thanks for the hint
