### ISSUE TITLE
socket timed out

### ISSUE THREAD

**Issue by hlj2722** [ASKBOT/askbot-devel#565]
When I run the  program ,the log is show error.

[01/Mar/2016 22:58:01] "GET /settings/GENERAL_SKIN_SETTINGS/ HTTP/1.1" 200 28228
[01/Mar/2016 22:58:01] "GET /jsi18n/ HTTP/1.1" 200 4265
[01/Mar/2016 22:58:01] "GET /m/default/media/images/logo.gif?v=1 HTTP/1.1" 200 2249
[01/Mar/2016 22:58:01] "GET /m/default/media/images/pw-login.gif?v=1 HTTP/1.1" 200 1818
[01/Mar/2016 22:58:01] "GET /m/default/media/images/favicon.gif?v=1 HTTP/1.1" 304 0
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 43257)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.9-py2.7.egg/django/core/servers/basehttp.py", line 102, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.8.9-py2.7.egg/django/core/servers/basehttp.py", line 167, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out

**Comment by evgenyfadeev** [comment]
Does this happen when you use "runserver" command?

**Comment by hlj2722** [comment]
Yes, I am running in python manage runserver

**Comment by evgenyfadeev** [comment]
This can happen as runserver is not meant to serve under high load. When
application is called by the browser for the first time it might request
lot's of static files in a short period of time and overwhelm the
development server.

On Fri, Mar 11, 2016 at 10:02 AM, hlj2722 <notifications@github.com> wrote:

> Yes, I am running in python manage runserver
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ASKBOT/askbot-devel/issues/565#issuecomment-195226523>
> .
>



-- 
Askbot
Valparaiso, Chile
skype: evgeny-fadeev
