### ISSUE TITLE
Deleting users

### ISSUE THREAD

**Issue by MarcJose** [ASKBOT/askbot-devel#578]
Deleting users on `/admin/auth/user/` gives an error:
```
mod_wsgi (pid=6260): Exception occurred processing WSGI script '/var/www/html/ss16/forum_askbot/django.wsgi'.
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/Django-1.5-py2.7.egg/django/core/handlers/wsgi.py", line 255, in __call__
response = self.get_response(request)
File "/usr/lib/python2.7/site-packages/Django-1.5-py2.7.egg/django/core/handlers/base.py", line 178, in get_response
response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
File "/usr/lib/python2.7/site-packages/Django-1.5-py2.7.egg/django/core/handlers/base.py", line 224, in handle_uncaught_exception
eturn callback(request, **param_dict)
File "/usr/lib/python2.7/site-packages/Django-1.5-py2.7.egg/django/utils/decorators.py", line 91, in _wrapped_view
response = view_func(request, *args, **kwargs)
File "/usr/lib/python2.7/site-packages/Django-1.5-py2.7.egg/django/views/defaults.py", line 41, in server_error
return http.HttpResponseServerError(template.render(Context({})))
File "/usr/lib/python2.7/site-packages/Coffin-0.3.8-py2.7.egg/coffin/template/__init__.py", line 55, in render
return super(Template, self).render(**context)
File "/usr/lib/python2.7/site-packages/Jinja2-2.7.2-py2.7.egg/jinja2/environment.py", line 969, in render
 return self.environment.handle_exception(exc_info, True)
File "/usr/lib/python2.7/site-packages/Jinja2-2.7.2-py2.7.egg/jinja2/environment.py", line 742, in handle_exception
reraise(exc_type, exc_value, tb)
File "/var/www/html/askbot_files/askbot/templates/500.html", line 1, in top-level template code
 {% extends "two_column_body.html" %}
File "/var/www/html/askbot_files/askbot/templates/two_column_body.html", line 1, in top-level template code
 {% extends "base.html" %}
File "/var/www/html/askbot_files/askbot/templates/base.html", line 27, in top-level template code
{% include "meta/html_head_stylesheets.html" %}
File "/var/www/html/askbot_files/askbot/templates/meta/html_head_stylesheets.html", line 7, in top-level template code
{% compress css %}
File "/usr/lib/python2.7/site-packages/django_compressor-1.2-py2.7.egg/compressor/contrib/jinja2ext.py", line 40, in _compress
original_content = caller()
File "/var/www/html/askbot_files/askbot/templates/meta/html_head_stylesheets.html", line 9, in template
 {{ skin.get_extra_css_link() }}
File "/usr/lib/python2.7/site-packages/Jinja2-2.7.2-py2.7.egg/jinja2/environment.py", line 397, in getattr
return getattr(obj, attribute)
UndefinedError: 'skin' is undefined
```
Enabling debug I get:
```
DatabaseError at /admin/auth/user/
relation "group_messaging_lastvisittime" does not exist
LINE 1: ...r_handle", "auth_user"."social_sharing_mode" FROM "group_mes...
                                                             ^
Request Method:	POST
Request URL:	my.site.com/admin/auth/user/
Django Version:	1.5
Exception Type:	DatabaseError
Exception Value:	
relation "group_messaging_lastvisittime" does not exist
LINE 1: ...r_handle", "auth_user"."social_sharing_mode" FROM "group_mes...
                                                             ^
Exception Location:	/usr/lib/python2.7/site-packages/Django-1.5-py2.7.egg/django/db/backends/postgresql_psycopg2/base.py in execute, line 54
Python Executable:	/usr/bin/python
Python Version:	2.7.5
```

**Comment by evgenyfadeev** [comment]
this most likely means that the databases weren't fully migrated.
