### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by MengJueM** [ASKBOT/askbot-devel#619]
Background: `pip install askbot`

when I executed the command: `python manage.py createsuperuser`, I got the following errors:

```
WARNING!!! You are using a 'locmem' (local memory) caching backend,
which is OK for a low volume site running on a single-process server.
For a multi-process configuration it is neccessary to have a production
cache system, such as redis or memcached.

With local memory caching and multi-process setup you might intermittently
see outdated content on your site.

System check identified some issues:

WARNINGS:
django_authopenid.UserPasswordQueue.user: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
group_messaging.SenderList.recipient: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
You have requested a flush of the database.
This will IRREVERSIBLY DESTROY all data currently in the 'petqa_db' database,
and return each table to an empty state.
Are you sure you want to do this?

    Type 'yes' to continue, or 'no' to cancel: yes
(venv)root@localhost:/opt/petqa/petqa_root# python manage.py createsuperuser
WARNING!!! You are using a 'locmem' (local memory) caching backend,
which is OK for a low volume site running on a single-process server.
For a multi-process configuration it is neccessary to have a production
cache system, such as redis or memcached.

With local memory caching and multi-process setup you might intermittently
see outdated content on your site.

System check identified some issues:

WARNINGS:
django_authopenid.UserPasswordQueue.user: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
group_messaging.SenderList.recipient: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
Username (leave blank to use 'root'): 
Email address: 
Password: 
Password (again): 
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/petqa/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/opt/petqa/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/petqa/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/petqa/venv/local/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 50, in execute
    return super(Command, self).execute(*args, **options)
  File "/opt/petqa/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/petqa/venv/local/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 149, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
  File "/opt/petqa/venv/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 191, in create_superuser
    **extra_fields)
  File "/opt/petqa/venv/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 182, in _create_user
    user.save(using=self._db)
  File "/opt/petqa/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/petqa/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 771, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/opt/petqa/venv/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/opt/petqa/venv/local/lib/python2.7/site-packages/askbot/models/__init__.py", line 3919, in add_missing_subscriptions
    instance.add_missing_askbot_subscriptions()
  File "/opt/petqa/venv/local/lib/python2.7/site-packages/askbot/models/__init__.py", line 2370, in user_add_missing_askbot_subscriptions
    form = forms.EditUserEmailFeedsForm()
  File "/opt/petqa/venv/local/lib/python2.7/site-packages/askbot/forms.py", line 1606, in __init__
    ('asked_by_me', EmailFeedSettingField(label=askbot_settings.WORDS_ASKED_BY_ME)),
  File "/opt/petqa/venv/local/lib/python2.7/site-packages/askbot/conf/settings_wrapper.py", line 66, in __getattr__
    return getattr(self.__instance, key).value
  File "/opt/petqa/venv/local/lib/python2.7/site-packages/askbot/deps/livesettings/values.py", line 457, in value
    val = self._value()
  File "/opt/petqa/venv/local/lib/python2.7/site-packages/askbot/deps/livesettings/values.py", line 348, in _value
    key += '_' + format_setting_name(lang)
  File "/opt/petqa/venv/local/lib/python2.7/site-packages/askbot/utils/functions.py", line 47, in format_setting_name
    token = token.replace(' ', '_')
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by evgenyfadeev** [comment]
Could you give specific steps to reproduce? Issue 544 had the same symptom, but was fixed some time ago.
