### ISSUE TITLE
metaclass conflict when I start with docker

### ISSUE THREAD

**Issue by gongxiuj** [ASKBOT/askbot-devel#721]
when i try start with docker use Dockerfile
`docker build -t lxw/askbot .`

when `python manage.py migrate --noinput`

`Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/site-packages/askbot-0.10.2-py2.7.egg/askbot/models/__init__.py", line 2, in <module>
    startup_procedures.run()
  File "/usr/local/lib/python2.7/site-packages/askbot-0.10.2-py2.7.egg/askbot/startup_procedures.py", line 1083, in run
    run_startup_tests()
  File "/usr/local/lib/python2.7/site-packages/askbot-0.10.2-py2.7.egg/askbot/startup_procedures.py", line 1009, in run_startup_tests
    test_modules()
  File "/usr/local/lib/python2.7/site-packages/askbot-0.10.2-py2.7.egg/askbot/startup_procedures.py", line 289, in test_modules
    try_import(mod_name, pip_path)
  File "/usr/local/lib/python2.7/site-packages/askbot-0.10.2-py2.7.egg/askbot/startup_procedures.py", line 209, in try_import
    load_module(module_name)
  File "/usr/local/lib/python2.7/site-packages/askbot-0.10.2-py2.7.egg/askbot/utils/loading.py", line 23, in load_module
    return __import__(mod_path, globals(), locals(), [], -1)
  File "/usr/local/lib/python2.7/site-packages/picklefield/__init__.py", line 5, in <module>
    from picklefield.fields import PickledObjectField # reexport
  File "/usr/local/lib/python2.7/site-packages/picklefield/fields.py", line 79, in <module>
    class PickledObjectField(_get_subfield_superclass()):
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/subclassing.py", line 24, in __new__
    new_class = super(SubfieldBase, cls).__new__(cls, name, bases, attrs)
TypeError: Error when calling the metaclass bases
metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases`

**Comment by lxw0109** [comment]
I came across the same problem when using the newest version of the code.

**Comment by MichaelPereira** [comment]
The current setup option do not allow for easy customization of the DB parameters, so the current Dockerfile cannot be used to generate images that can connect to databases outside of the local containers without manual changes.

I'm proposing changes in #712 that will allow such configuration to be done, and will make it easier to start an askbot container with a local database to get a working version of the project with just one command.

**Comment by delete** [comment]
I came across with this same problem today when deploying a new version.

After looking into some logs, we realize that "six" lib updated two days ago from **1.10.0** to **1.11.0**. And some broken after the update. You can see this issue [210](https://github.com/benjaminp/six/issues/210).

A rollback to version **1.10.0** solved my the problem for me.

**Comment by lxw0109** [comment]
@delete Thank you for your help. It solved my problem too.  : )

**Comment by gongxiuj** [comment]
@delete Thank you very much.
