### ISSUE TITLE
AdminEmailHandler sends user's passwords per e-mail

### ISSUE THREAD

**Issue by sebastian-philipp** [ASKBOT/askbot-devel#756]
I got something like this per mail:

```
Internal Server Error: /account/signin/
Traceback (most recent call last):
  File "/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/askbot/deps/django_authopenid/views.py", line 504, in signin
    password=password,
  File "/django/contrib/auth/__init__.py", line 74, in authenticate
    user = backend.authenticate(**credentials)
  File "/askbot/deps/django_authopenid/backends.py", line 46, in authenticate
    return self.auth_by_ldap(kwargs['username'], kwargs['password'])
  File "/askbot/deps/django_authopenid/backends.py", line 217, in auth_by_ldap
    assoc = ldap_create_user(user_info)
  File "/askbot/deps/django_authopenid/ldap_auth.py", line 188, in ldap_create_user_default
    user.save()
  File "/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
IntegrityError: duplicate key value violates unique constraint "auth_user_username_key"
DETAIL:  Key (username)=(my-user) already exists.


Request repr(): 
<WSGIRequest
path:/account/signin/,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'username': [u'my-user'], u'password': [u'secret-password'], u'persona_assertion': [u''], u'password_action': [u'login'], u'login_provider_name': [u'local'], u'login_with_password': [u'Sign in'], u'csrfmiddlewaretoken': [u'my-csrftoken'], u'next': [u'/']}>,
COOKIES:{'csrftoken': 'my-csrftoken',
 'sessionid': 'vg65e9ankg5muhhyeoyv2fa6pr6mkzwu'},
META:{'CONTENT_LENGTH': '248',
...snip...
 'wsgi.version': (1, 0)}>
```
The exact reason't doesn't matter right now, but **Askbot must not send user's passwords by e-mail**.

**Comment by omerfarukdogan** [comment]
Had the same issue.
