### ISSUE TITLE
Django 2.2 and python 3.6 - branch 0.11.x is this in working condition?

### ISSUE THREAD

**Issue by VishmiVishara** [ASKBOT/askbot-devel#815]
@evgenyfadeev please help. can I just clone it and use? I couldn't make it to run. askbot-setup is not working due to version changes of python and django.

Could you please give some instructions to setup the project with branch 0.11.x.

Thanks!

**Comment by martin-bts** [comment]
We are not yet done merging `0.11.x`. Especially the PR https://github.com/ASKBOT/askbot-devel/pull/813, which will enable Django2.2 has not been merged yet. Depending on Evgeny's availability it will be a few more days until `0.11.x` can be deployed. If you subscribe to this issue (button on the right), we can notify you as soon as `0.11.x` can be deployed.

**Comment by VishmiVishara** [comment]
sure, Thank you very much.

**Comment by martin-bts** [comment]
As of last night, branch 0.11.x is deployable.

- Running `askbot-setup` creates a Django project and an Askbot app inside this new project. For an example use see the Dockerfile. 
- Using the Dockerfile, i.e. images built from it, currently only works with Postgresql as a backend.
- See `askbot/container/docker-compose.yml` for an example on how to deploy Askbot with Postgresql.
- To build an image suited for use with `askbot/container/docker-compose.yml` switch to the top directory, i.e. the one containing the `Dockerfile`, `askbot_requirements.txt`, etc. and run

      docker build -t askbot:latest --build-arg ASKBOT=. .

**Comment by VishmiVishara** [comment]
@martin-bts Thank you very much for the information and the continues help.

I tried setting up by typing `askbot-setup` Its installing version `askbot 0.10.2`.
Could you please explain setting up askbot 0.11.x version. It's not creating Django project too.

**Comment by martin-bts** [comment]
For this kind of trouble there is the [Askbot support](https://askbot.org/en/questions/). When you ask for help there, please be detailed about what

- what you need help with
- what you did to end up in the current state (including cli commands and their output),
- which results you expected and
- which results you actually get.

**Comment by VishmiVishara** [comment]
Thank you very much

**Comment by VishmiVishara** [comment]
Thanks! according to the other changes, `setup.py`, and other setup file still not updated.

**Comment by VishmiVishara** [comment]
before run `askbot-setup` we should run `python setup.py develop` ? it's installing `askbot 0.10.2` then after running `askbot-setup` It's giving error 

`Traceback (most recent call last):
  File "/home/admin_qna/askbot/askbotenv_new_3.6_new/bin/askbot-setup", line 11, in <module>
    load_entry_point('askbot', 'console_scripts', 'askbot-setup')()
  File "/opt/askbot-devel/askbot/deployment/__init__.py", line 216, in __call__
    directory = path_utils.get_install_directory(force=options.get('force')) # i.e. ask the user
AttributeError: 'Namespace' object has no attribute 'get'`

**Comment by sebastian-philipp** [comment]
@VishmiVishara did you run askbot-setup in a virtual environment, like venv?

**Comment by VishmiVishara** [comment]
yes, it's a virtual environment

**Comment by sebastian-philipp** [comment]
could you join us on Freenode IRC #askbot ? GH Issue comments have a low bandwidth for this kind of support

**Comment by EvanCarroll** [comment]
@VishmiVishara  I opened up another issue. I'm getting that too #832
