### ISSUE TITLE
0.11.x: ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by EvanCarroll** [ASKBOT/askbot-devel#837]
when running `setup.py`

```
....
Running django-livesettings3-1.4.19/setup.py -q bdist_egg --dist-dir /tmp/easy_install-hztxck_1/django-livesettings3-1.4.19/egg-dist-tmp-jgyb1vsn     
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules                                                              
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context                                                             
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup                                                                 
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile                                                                  
    exec(code, globals, locals)
  File "/tmp/easy_install-hztxck_1/django-livesettings3-1.4.19/setup.py", line 24, in <module>                                                        
    ]
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup                                                                    
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 220, in run                                                             
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 273, in zip_safe                                                        
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 383, in analyze_egg                                                     
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 422, in scan_module                                                     
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)

```

**Comment by martin-bts** [comment]
I am having trouble reproducting this and this looks like a problem with installing `django-livesettings3`. Can you try splitting this into separate steps? First install livesettings and Askbots afterwards. Does the problem persist with that approach?
