### ISSUE TITLE
Getting a Traceback error when running askbot-setup

### ISSUE THREAD

**Issue by Lauren15468** [ASKBOT/askbot-devel#839]
now what I do is:
git clone git://github.com/ASKBOT/askbot-devel.git <project_name>
git checkout 0.11.x
sudo python3 setup.py develop

which both work but then I do:
askbot-setup and I get

Traceback (most recent call last):
File "/srv/askbot_2/venv/bin/askbot-setup", line 6, in 
from pkg_resources import load_entry_point
File "/srv/askbot_2/venv/local/lib/python2.7/site-packages/pkg_resources/init.py", line 3250, in 
@_call_aside
File "/srv/askbot_2/venv/local/lib/python2.7/site-packages/pkg_resources/init.py", line 3234, in _call_aside
f(*args, **kwargs)
File "/srv/askbot_2/venv/local/lib/python2.7/site-packages/pkg_resources/init.py", line 3263, in _initialize_master_working_set
working_set = WorkingSet._build_master()
File "/srv/askbot_2/venv/local/lib/python2.7/site-packages/pkg_resources/init.py", line 583, in _build_master
ws.require(requires)
File "/srv/askbot_2/venv/local/lib/python2.7/site-packages/pkg_resources/init.py", line 900, in require
needed = self.resolve(parse_requirements(requirements))
File "/srv/askbot_2/venv/local/lib/python2.7/site-packages/pkg_resources/init.py", line 786, in resolve
raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'responses>=0.9.0' distribution was not found and is required by askbot

I would get a similar error with python setup.py develop as well.

Any suggestions to fix this would be greatly appreciated.

**Comment by sebastian-philipp** [comment]
@ martin-bts  any idea?

**Comment by Lauren15468** [comment]
also may be important to note I did:

sudo python3 setup.py develop instead of sudo python setup.py develop so I wouldn't get the traceback error here too.

**Comment by sebastian-philipp** [comment]
fyi, Askbot .0.11.x is no longer compatible to Python 2

**Comment by Lauren15468** [comment]
is there a working branch for ubuntu 18.04 ?

**Comment by martin-bts** [comment]
It would seem that in this case calling `askbot-setup` implicitly calls Python 2 which cannot work on the 0.11.x branch.

For using the 0.11.x branch I would suggest using the Dockerfile, i.e. a container. This has the highest chance of success. The installer is being rewritten at the moment and it will be a few weeks until we're done.

**Comment by Lauren15468** [comment]
oh ok. Is there a branch where a container isn't needed?

**Comment by sebastian-philipp** [comment]
Yeah, I've been there, done that. I suggest deploying Askbot in a container. You just don't want to do the manual way.

**Comment by martin-bts** [comment]
There are the master branch and the pypi package referred to in the computingforgeeks.com article.

I am a bit confused about the usage of `sudo` in the initial message. To me this looks like you are not using a virtual environment and therefore are not following the tutorial. Maybe using a virtual environment fixes the problem? A Python3 venv would be required for the 0.11.x branch. In my deployments I do (from the top of my head) :

- install
- askbot-setup
- migrate
- collectstatic

**Comment by martin-bts** [comment]
As `askbot-setup` is virtually rewritten from scratch, we will not address this issue anymore. I suggest closing this.

**Comment by martin-bts** [comment]
This refers to a piece of code that is no longer part of Askbot. I suggest closing this issue, because it is not relevant anymore.
