### ISSUE TITLE
Error when running manage.py

### ISSUE THREAD

**Issue by teavanist** [ASKBOT/askbot-devel#878]
I get the following error when running manage.py collectstatic
Ubuntu 16, Python 2.7, Postgresql 
Installation done using pip install askbot and then accoridng to instructions in initial-configuration.rst

==============
root@ubuntu:~/mydjangosite# python manage.py collectstatic
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/compressor/models.py", line 1, in <module>
    from compressor.conf import CompressorConf  # noqa
  File "/usr/local/lib/python2.7/dist-packages/compressor/conf.py", line 6, in <module>
    from appconf import AppConf
  File "/usr/local/lib/python2.7/dist-packages/appconf/__init__.py", line 1, in <module>
    from .base import AppConf  # noqa
  File "/usr/local/lib/python2.7/dist-packages/appconf/base.py", line 107
    class AppConf(metaclass=AppConfMetaClass):

**Comment by evgenyfadeev** [comment]
These issues are resolved now. Try tips of any 0.7.x - 0.10.x, master branch.

Fixed in version 0.11.0, 0.10.3, 0.9.4, 0.8.3, 0.7.59.
