### ISSUE TITLE
Invalid tag `trans`

### ISSUE THREAD

**Issue by mzch** [ASKBOT/askbot-devel#879]
When clicking `Recover Account` button, the following error occurred.

```python
Internal Server Error: /account/recover/
Traceback (most recent call last):
  File "/srv/askbot/.pyenv/versions/3.7.9/lib/python3.7/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'trans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/askbot/.pyenv/versions/3.7.9/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/srv/askbot/.pyenv/versions/3.7.9/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/srv/askbot/.pyenv/versions/3.7.9/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/askbot/.pyenv/versions/3.7.9/lib/python3.7/site-packages/askbot-0.11.0-py3.7.egg/askbot/deps/django_authopenid/views.py", line 1499, in recover_account
    send_user_new_email_key(user)
  File "/srv/askbot/.pyenv/versions/3.7.9/lib/python3.7/site-packages/askbot-0.11.0-py3.7.egg/askbot/deps/django_authopenid/views.py", line 1481, in send_user_new_email_key
    send_email_key(user.email, user.email_key)
  File "/srv/askbot/.pyenv/versions/3.7.9/lib/python3.7/site-packages/askbot-0.11.0-py3.7.egg/askbot/deps/django_authopenid/views.py", line 1476, in send_email_key
    email.send([address,])
  File "/srv/askbot/.pyenv/versions/3.7.9/lib/python3.7/site-packages/askbot-0.11.0-py3.7.egg/askbot/mail/messages.py", line 140, in send
    subject_line=self.render_subject(),
  File "/srv/askbot/.pyenv/versions/3.7.9/lib/python3.7/site-packages/askbot-0.11.0-py3.7.egg/askbot/mail/messages.py", line 122, in render_subject
    template = get_template(self.template_path + '/subject.txt')
  File "/srv/askbot/.pyenv/versions/3.7.9/lib/python3.7/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/srv/askbot/.pyenv/versions/3.7.9/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/srv/askbot/.pyenv/versions/3.7.9/lib/python3.7/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/srv/askbot/.pyenv/versions/3.7.9/lib/python3.7/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/srv/askbot/.pyenv/versions/3.7.9/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/srv/askbot/.pyenv/versions/3.7.9/lib/python3.7/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/srv/askbot/.pyenv/versions/3.7.9/lib/python3.7/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/srv/askbot/.pyenv/versions/3.7.9/lib/python3.7/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/srv/askbot/.pyenv/versions/3.7.9/lib/python3.7/site-packages/django/template/base.py", line 534, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 1: 'trans'. Did you forget to register or load this tag?
```

- Python: `3.7.9` and `3.8.5`
- `master`branch

**Comment by evgenyfadeev** [comment]
Fixed, made a bug fix release 0.11.1. There are likely more bugs in this branch... Thanks.
