### ISSUE TITLE
New error in master: ModuleNotFoundError: No module named 'AskbotMessaging'

### ISSUE THREAD

**Issue by EvanCarroll** [ASKBOT/askbot-devel#908]
Getting this error now with Master.

> ModuleNotFoundError: No module named 'AskbotMessaging'

```text
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/Django-3.2.14-py3.7.egg/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/Django-3.2.14-py3.7.egg/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/local/lib/python3.7/site-packages/Django-3.2.14-py3.7.egg/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/site-packages/Django-3.2.14-py3.7.egg/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.7/site-packages/Django-3.2.14-py3.7.egg/django/apps/config.py", line 250, in create
    app_config_class.__qualname__,
django.core.exceptions.ImproperlyConfigured: Cannot import 'AskbotMessaging'. Check that 'askbot.deps.group_messaging.apps.AskbotConfig.name' is correct.
/srv/askbot_site # 
/srv/askbot_site # python manage.py check
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/Django-3.2.14-py3.7.egg/django/apps/config.py", line 244, in create
    app_module = import_module(app_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'AskbotMessaging'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/Django-3.2.14-py3.7.egg/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/Django-3.2.14-py3.7.egg/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/local/lib/python3.7/site-packages/Django-3.2.14-py3.7.egg/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/site-packages/Django-3.2.14-py3.7.egg/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.7/site-packages/Django-3.2.14-py3.7.egg/django/apps/config.py", line 250, in create
    app_config_class.__qualname__,
django.core.exceptions.ImproperlyConfigured: Cannot import 'AskbotMessaging'. Check that 'askbot.deps.group_messaging.apps.AskbotConfig.name' is correct.
```

**Comment by evgenyfadeev** [comment]
Yes I've noticed. Working currently on removing the group_messaging dependency.

**Comment by EvanCarroll** [comment]
Cool. Didn't mean to get in the way. BTW, trying to create a Kubernetes operator for AskBot. If I can get it working I can also take the CI stuff I have and submit a PR so you'll at least know if the PRs break install.

**Comment by evgenyfadeev** [comment]
Great, would be good to configure a testing CI. 

I've just commented out the askbot_messaging, it's no longer getting in the way of running the app. There are some non-critical test case failures ATM and afaik, the moderation window is broken. Otherwise the master branch should be usable now (In Python 3.7 - I'll restrict just to this version for now, 3.6 started giving errors in the configuration stage).

**Comment by EvanCarroll** [comment]
That works!
